kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mlflow-service
spec:
  to:
    kind: Service
    name: mlflow-service
    weight: 100
  port:
    targetPort: 5000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
