kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: prometheus-service
spec:
  to:
    kind: Service
    name: prometheus-service
    weight: 100
  port:
    targetPort: 9090
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
