apiVersion: v1
kind: Service
metadata:
  name: numalogic-redis-cluster
spec:
  ports:
    - name: redis
      nodePort: 0
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    name: numalogic-redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
